# Generated by Django 5.1.3 on 2024-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cover',
            field=models.ImageField(blank=True, default='default/image_default.png', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
