# Generated by Django 5.1.3 on 2024-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='products',
        ),
        migrations.AddField(
            model_name='ordered',
            name='products',
            field=models.ManyToManyField(related_name='ordered', to='home.cartitem'),
        ),
    ]
