# Generated by Django 5.1.3 on 2024-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_ordered_products_ordered_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='firs_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='house_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='number_ordered',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='street_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='products',
            field=models.ManyToManyField(null=True, related_name='ordered', to='home.cartitem'),
        ),
    ]
