# Generated by Django 5.1.3 on 2024-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_ordered_firs_name_ordered_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='firs_name',
        ),
        migrations.AddField(
            model_name='ordered',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='house_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='number_ordered',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='products',
            field=models.ManyToManyField(default='', related_name='ordered', to='home.cartitem'),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='street_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
