# Generated by Django 5.1.3 on 2024-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_ordered_first_name_alter_ordered_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='products',
            field=models.ManyToManyField(null=True, related_name='ordered', to='home.cartitem'),
        ),
    ]
