# Generated by Django 5.1.3 on 2024-12-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_ordered_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='number_ordered',
        ),
    ]
