# Generated by Django 5.1.3 on 2024-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_ordered_number_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='number_ordered',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
