# Generated by Django 5.1.3 on 2024-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_cartitem_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
