# Generated by Django 5.1.3 on 2024-12-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_ordered_neighborhood_alter_ordered_last_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
    ]
