# Generated by Django 5.1.3 on 2024-12-12 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='house_number',
        ),
        migrations.AddField(
            model_name='ordered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
