# Generated by Django 5.1.3 on 2024-12-17 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_ordered_house_number_customerquestions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerQuestions',
            new_name='CustomerQuestion',
        ),
    ]
