# Generated by Django 5.1.3 on 2025-01-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
