# Generated by Django 5.1.3 on 2025-03-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_cartitem_cart_remove_cartitem_is_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
