# Generated by Django 5.1.3 on 2025-03-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_ordered_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='number_ordered',
        ),
    ]
